# Extra workspaces 11-20 with SUPER + CTRL + [1-9; 0]
bindd = SUPER CTRL, code:10, Switch to workspace 11, workspace, 11
bindd = SUPER CTRL, code:11, Switch to workspace 12, workspace, 12
bindd = SUPER CTRL, code:12, Switch to workspace 13, workspace, 13
bindd = SUPER CTRL, code:13, Switch to workspace 14, workspace, 14
bindd = SUPER CTRL, code:14, Switch to workspace 15, workspace, 15
bindd = SUPER CTRL, code:15, Switch to workspace 16, workspace, 16
bindd = SUPER CTRL, code:16, Switch to workspace 17, workspace, 17
bindd = SUPER CTRL, code:17, Switch to workspace 18, workspace, 18
bindd = SUPER CTRL, code:18, Switch to workspace 19, workspace, 19
bindd = SUPER CTRL, code:19, Switch to workspace 20, workspace, 20

# Move active window to workspace 11-20 with SUPER + CTRL + SHIFT + [1-9; 0]
bindd = SUPER CTRL SHIFT, code:10, Move window to workspace 11, movetoworkspace, 11
bindd = SUPER CTRL SHIFT, code:11, Move window to workspace 12, movetoworkspace, 12
bindd = SUPER CTRL SHIFT, code:12, Move window to workspace 13, movetoworkspace, 13
bindd = SUPER CTRL SHIFT, code:13, Move window to workspace 14, movetoworkspace, 14
bindd = SUPER CTRL SHIFT, code:14, Move window to workspace 15, movetoworkspace, 15
bindd = SUPER CTRL SHIFT, code:15, Move window to workspace 16, movetoworkspace, 16
bindd = SUPER CTRL SHIFT, code:16, Move window to workspace 17, movetoworkspace, 17
bindd = SUPER CTRL SHIFT, code:17, Move window to workspace 18, movetoworkspace, 18
bindd = SUPER CTRL SHIFT, code:18, Move window to workspace 19, movetoworkspace, 19
bindd = SUPER CTRL SHIFT, code:19, Move window to workspace 20, movetoworkspace, 20
